services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: zookeeper
    ports:
      - "2182:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./zk-data:/var/lib/zookeeper/data \
      - ./zk-txn-logs:/var/lib/zookeeper/log \

  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka1
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092, PLAINTEXT_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka2:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka2
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092, PLAINTEXT_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REPLICATION_FACTOR: 1

  kafka3:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka3
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, PLAINTEXT_HOST://0.0.0.0:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092, PLAINTEXT_HOST://localhost:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REPLICATION_FACTOR: 1

  postgres_db:
    image: postgres:16
    container_name: user_info_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: internship_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5433:5432"

  mongo_db:
    image: mongo:8.0.3
    container_name: doc_storage_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: file_storage

  user_service:
    build:
      context: ./user_service
    restart: always
    env_file:
      - .env_users_non_dev
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres_db
    ports:
      - "8000:8000"

  doc_storage_service:
    build:
      context: ./doc_storage_service
    restart: always
    env_file:
      - .env_doc_stor_non_dev
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - mongo_db
    ports:
      - "8001:8001"

volumes:
  postgresdata:
  mongo_data:
